import React, { useState, useEffect } from 'react';
import { Link } from 'react-router-dom';

export default function TimelineItem({ frontmatter, isLast }) {
  const { date, linked_title, filename, description, category, images } = frontmatter;
  const autoGeneratedUrl = filename ? `/articles/${filename}` : '#';

  // --- 幻灯片 (Lightbox) 状态管理 ---
  const [isLightboxOpen, setIsLightboxOpen] = useState(false);
  const [currentIndex, setCurrentIndex] = useState(0);

  // 确保 images 是一个数组（如果 md 里没写 images，就给个空数组防崩溃）
  const imageList = Array.isArray(images) ? images : [];
  
  // 计算缩略图逻辑：只取前 6 张，计算剩余数量
  const displayImages = imageList.slice(0, 6);
  const extraCount = imageList.length - 6;

  // 交互动作：打开、关闭、上一张、下一张
  const openLightbox = (index) => {
    setCurrentIndex(index);
    setIsLightboxOpen(true);
  };
  const closeLightbox = () => setIsLightboxOpen(false);
  
  const goToPrevious = (e) => {
    e.stopPropagation(); // 阻止点击事件冒泡到背景导致关闭
    setCurrentIndex((prevIndex) => (prevIndex === 0 ? imageList.length - 1 : prevIndex - 1));
  };
  
  const goToNext = (e) => {
    e.stopPropagation();
    setCurrentIndex((prevIndex) => (prevIndex === imageList.length - 1 ? 0 : prevIndex + 1));
  };

  // 按 ESC 键也能关闭图片
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === 'Escape') closeLightbox();
    };
    if (isLightboxOpen) window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isLightboxOpen]);

  return (
    <div className="relative pl-8 pb-12">
      {/* 时间线样式 */}
      {!isLast && (
        <div className="absolute left-[5px] top-7 bottom-0 w-[2px] bg-gray-200"></div>
      )}
      <div className="absolute left-0 top-1.5 w-3 h-3 bg-white border-2 border-gray-400 rounded-full z-10 mt-[2px]"></div>

      <div className="mb-4">
        <span className="text-sm font-mono text-gray-400 tracking-wider">· {date}</span>
      </div>

      <div className="text-gray-700 leading-relaxed font-wenkai text-[15px] mb-5 whitespace-pre-wrap">
        {description}
      </div>

      {/* 文章卡片 */}
      {linked_title && (
        <Link className="block border border-gray-200 rounded-xl p-5 bg-white hover:border-gray-300 hover:shadow-sm transition-all duration-300 no-underline group max-w-lg mb-4" to={autoGeneratedUrl}>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-gray-400 group-hover:text-gray-600 transition-colors">✒️</span>
            <span className="text-xs text-gray-500 tracking-widest">{category || '随笔'}</span>
          </div>
          <h3 className="text-lg font-serif font-bold text-gray-900 m-0 group-hover:text-black transition-colors">
            《{linked_title}》
          </h3>
        </Link>
      )}

      {/* 🌟 缩略图画廊区 (Grid) */}
      {imageList.length > 0 && (
        <div className="grid grid-cols-3 gap-2 max-w-lg mt-2">
          {displayImages.map((src, index) => (
            <div 
              key={index} 
              className="relative aspect-square cursor-pointer overflow-hidden rounded-lg border border-gray-100 group"
              onClick={() => openLightbox(index)}
            >
              <img 
                src={src} 
                alt={`配图 ${index + 1}`} 
                className="w-full h-full object-cover group-hover:scale-105 transition-transform duration-500" 
              />
              {/* 如果是第 6 张图，且还有更多图片，渲染毛玻璃遮罩和数字 */}
              {index === 5 && extraCount > 0 && (
                <div className="absolute inset-0 bg-black/40 backdrop-blur-[2px] flex items-center justify-center text-white font-serif text-xl tracking-wider">
                  +{extraCount}
                </div>
              )}
            </div>
          ))}
        </div>
      )}

      {/* 🌟 沉浸式幻灯片放大镜 (Modal) */}
      {isLightboxOpen && imageList.length > 0 && (
        <div 
          className="fixed inset-0 z-[100] flex items-center justify-center bg-black/95 backdrop-blur-sm animate-fade-in"
          onClick={closeLightbox}
        >
          {/* 关闭按钮 */}
          <button className="absolute top-6 right-8 text-white/70 hover:text-white text-4xl font-light cursor-pointer border-none bg-transparent transition-colors z-[110]">
            &times;
          </button>

          {/* 上一张按钮 */}
          <button 
            onClick={goToPrevious} 
            className="absolute left-4 md:left-12 text-white/50 hover:text-white text-5xl p-4 cursor-pointer border-none bg-transparent transition-colors z-[110] select-none"
          >
            &#8249;
          </button>

          {/* 当前大图 */}
          <img 
            src={imageList[currentIndex]} 
            alt={`大图 ${currentIndex + 1}`} 
            className="max-h-[85vh] max-w-[85vw] object-contain rounded-md shadow-2xl select-none"
            onClick={(e) => e.stopPropagation()} // 点图片本身不会关闭
          />

          {/* 下一张按钮 */}
          <button 
            onClick={goToNext} 
            className="absolute right-4 md:right-12 text-white/50 hover:text-white text-5xl p-4 cursor-pointer border-none bg-transparent transition-colors z-[110] select-none"
          >
            &#8250;
          </button>

          {/* 进度计数器 */}
          <div className="absolute bottom-8 text-white/60 font-mono text-sm tracking-widest">
            {currentIndex + 1} / {imageList.length}
          </div>
        </div>
      )}
    </div>
  );
}